app/proctool/proctool/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('proctor/', include('proctor.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/proctool/proctor/urls.py
from django.conf.urls import url
from . import views

app_name = 'proctor'

urlpatterns = [
   url(r'^violation/$', views.get_violation, name="get_violation"),
   url(r'^test/$', views.test_view, name="test"),
   url(r'^submit/$', views.submit, name="submit"),
   url(r'^reportviolation/(?P<id>[\w-]+)/(?P<vio>[\w-]+)/$', views.report_violation, name="report-violation"),
   # url(r'^student-exam/$', views.student_exam, name="student-exam"),
]

app/proctool/users/urls.py
from django.conf.urls import url
from . import views

app_name = 'users'

urlpatterns = [
   url(r'^signup/$', views.signup_view, name="signup"),
   url(r'^login/$', views.login_view, name="login"),
   url(r'^logout/$', views.logout_view, name="logout"),
]

app/proctool/proctor/models.py
from django.db import models

# Create your models here.
class Violation(models.Model):
    multiperson = models.IntegerField(default=0, blank=False)
    fullscreen = models.IntegerField(default=0, blank=False)
    screenfocus = models.IntegerField(default=0, blank=False)
    audio = models.IntegerField(default=0, blank=False)
    facedir = models.IntegerField(default=0, blank=False)
    facesim = models.IntegerField(default=0, blank=False)
    othergadgets = models.IntegerField(default=0, blank=False)

app/proctool/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from proctor.models import Violation

ROLES = (
    ('Test Admin', 'Test Admin'),
    ('Candidate', 'Candidate'),
)

# Create your models here.

class MyAccountManager(BaseUserManager):
    use_in_migrations = True
    def create_user(self, email, username, password = None):
        if not email:
            raise ValueError('Users must have an mail id')
        if not username:
            raise ValueError('Users must have a username')
        user = self.model(
            email = self.normalize_email(email),
            username = username,
        )
        user.set_password(password)
        user.save(using = self._db)
        return user
    
    def create_superuser(self, email, username, password):
        user = self.create_user(
            email = self.normalize_email(email),
            password = password,
            username = username,
        )
    
        user.is_admin = True
        user.is_staff = True
        user.is_superuser = True
        user.save(using=self._db)
        return user
            

class Account(AbstractBaseUser):
    email = models.EmailField(verbose_name="email", max_length=60, unique=True)
    username = models.CharField(verbose_name='name', max_length=50, null=False)
    date_joined	= models.DateTimeField(verbose_name='date joined', auto_now_add=True)
    last_login = models.DateTimeField(verbose_name='last login', auto_now=True)
    is_admin = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)
    is_testadmin = models.BooleanField(default=False)
    violations = models.ForeignKey(Violation,on_delete=models.CASCADE, blank=True, null=True)
    thumb = models.ImageField(default='default.jpg')

    objects = MyAccountManager()
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username', 'thumb', ]

    def __str__(self):
        return self.email
    
    # For checking permissions. to keep it simple all admin have ALL permissons
    def has_perm(self, perm, obj=None):
        return self.is_admin

    # Does this user have permission to view this app? (ALWAYS YES FOR SIMPLICITY)
    def has_module_perms(self, app_label):
        return True

app/proctool/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm 
from django.contrib.auth import authenticate
from .models import *


class RegistrationForm(UserCreationForm):
    email = forms.EmailField(max_length = 60)
    thumb = forms.FileField()
    class Meta:
        model = Account
        fields = ('email', 'username', 'password1', 'password2', 'thumb')


class LoginForm(forms.ModelForm):
    password = forms.CharField(label='Password', widget=forms.PasswordInput)
    class Meta:
        model = Account
        fields = ('email', 'password')
    
    def clean(self):
        # email = self.cleaned_data['email'].lower()
        email = MyAccountManager.normalize_email(self.cleaned_data['email'])
        password = self.cleaned_data['password']
        if not authenticate(email = email, password = password):
            raise forms.ValidationError('Invalid Credentials')

app/proctool/proctor/views.py
from proctor.models import Violation
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from users.models import Account

def get_violation(request):
    users = Account.objects.all()[1:]
    # print(users[1].violations.fullscreen)
    context = {
        'users': users
    }
    return render(request, 'proctor/violations.html', context)
    

@login_required(login_url="/users/login/")
def test_view(request):
    user = request.user
    context = {'user':user}
    return render(request, 'proctor/test_page.html', context)


def report_violation(request,id,vio):
    user = Account.objects.get(pk=id)
    if vio == "multiperson":
        # print(user.violations.multiperson)
        user.violations.multiperson += 1
        # # print('Working**********')
        # print(user.violations.multiperson)
    elif vio == "fullscreen":
        user.violations.fullscreen += 1
    elif vio == "screenfocus":
        user.violations.screenfocus += 1
    elif vio == "audio":
        user.violations.audio += 1
    elif vio == "facedir":
        user.violations.facedir += 1
    elif vio == "facesim":
        user.violations.facesim += 1
    elif vio == "othergadgets":
        user.violations.othergadgets += 1
    else:
        print("Not Found")
    user.violations.save()
    return HttpResponse("Successful")
   
def submit(request):
    # user = request.user
    # logout(request)
    # print(user.is_active)
    # user.is_active = False
    # print(user.is_active)
    # user.save()
    return render(request, 'proctor/submit.html')





# def student_exam(request):
#     context = {}
#     return render(request, 'proctor/student_exam_page.html', context)

app/proctool/users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate, logout
from .forms import RegistrationForm, LoginForm
from .models import MyAccountManager, Account
from django.http import HttpResponse
from proctor.models import Violation

def signup_view(request):
    context = {}
    if request.method == 'POST':
        registration_form = RegistrationForm(request.POST, request.FILES)
        if registration_form.is_valid():
            account = registration_form.save()
            user = Account.objects.get(email=account.email)
            user.violations = Violation()
            user.save()
            login(request, account)
            return redirect('proctor:test')
            # return HttpResponse('Signed Up')
        else:
            context['form'] = registration_form
    else:
        form = RegistrationForm()
        context['form'] = form
    return render(request, 'users/home.html', context)
    


def login_view(request):
    context = {}
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            email = MyAccountManager.normalize_email(form.cleaned_data['email'])
            password = request.POST['password']
            user = authenticate(email = email, password = password)
            if user:
                login(request, user)
                return redirect('proctor:test')
                # return HttpResponse('Logged In')
    else:
        form = LoginForm()
    context['form'] = form
    return render(request, 'users/home.html', context)

def logout_view(request):
        logout(request)
        return redirect('users:login')

app/proctool/proctor/templates/proctor/submit.html
<html >
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Exam Submitted - ProcExam</title>
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <!-- Font special for pages-->
  <link href="https://fonts.googleapis.com/css?family=Poppins:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
    <style>
    div.Bg_color {
    background-image: url("https://i.ibb.co/TtMK72c/bg.jpg");
    width: 100%;
    height: 90%;
    -webkit-background-size: cover;
        -moz-background-size: cover;
        -o-background-size: cover;
        background-size: cover;
}



.text {
    width: 40%;
    height: 45%;
    background-color:white;
    position: absolute;
    margin-left: 30%;
    margin-top: -7%;
    border: 2px solid gray;
    border-radius: 10px;
    box-shadow: 0px 7px 3px #55d6aa, 0px -7px 3px #55d6aa;
}



#thank {
    font-size: 20px;
}

#button {
    position: relative;
    width: 120px;
    height: 40px;
    margin-top:40px;
    background-color: #55d6aa;
    color: white;
}

nav {
  float: right;
}

nav ul {
  margin: 0;
  padding: 0;
  list-style: none;
}

nav li {
  display: inline-block;
  margin-left: 70px;
  position: relative;
}

header {
  background: #55d6aa;
}

footer {

  width:100%;
  text-align: center;
  background-color: #55d6aa;
  color: black;

}

    </style>
</head>
  <header >
    <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.0.0/css/font-awesome.min.css">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
  <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
  <script src="https://kit.fontawesome.com/14e9a22ec9.js" crossorigin="anonymous"></script>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>

  
  <div class="container" style="float: left;margin-left:0px;width:100%;height:8%;background-color: #55d6aa;">  
    <nav style="float: left;margin-left:0px;width:100%">
    <ul style="float: left;margin-left:0px;width:100%">
      
   
      <li style="margin-left:0px"><img style="width:150px;height:70px;margin-top:8px;margin-right:0px" src="https://i.ibb.co/dPNsksr/ProcExam.png"/></li>
      <li style="margin-left:0px;"><p style="font-family:roboto,garamond,serif;font-size:25px;"></li>
      <li style="float: right;margin-top:4px;margin-right:0px"><p id="my_msg" style="margin-top:14px;float: right;margin-left: 5px;"></p></li>
      <li style="float: right;margin-top:4px;margin-right:0px;text-align:center;"></li>
      <li>
    </ul>
  </nav>
   
  </div>
  </header>
<body>
    
        <center><div class="Bg_color"><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
            <div class="text" >
                <center><br><b style="font-size:60px">You've finished the test </b> <center>
                    <center><p id="thank" >Your responses and score has been saved. </p>  </center>    
                    <center><p id="thank">Your percentage score is <b>85%</b>.</p> </center>
                    <center><p id="thank">Thank for appearing in the exam. </p> </center>
                    <center><p id = "thank">You can now close this window.</p></center>
                </p>
                <center><button style="border-radius:20px" id="button">View Score</button> </center>
            </div>

        </div></center>
        
</body>
<footer style="width: 100%;">
    <p style = "color:white;font-family: Poppins, sans-serif;font-size:18px;">For any queries/issues contact: </p>
    <p style = "color:white;font-family: Poppins, sans-serif;font-size:18px;">(+1) 234567890 (Test Admin)</p>
    <p style = "color:white;font-family: Poppins, sans-serif;font-size:18px;"><a>test_admin@procexam.com</a></p>
</footer>
</html>

app/proctool/users/templates/users/home.html
<html>
  <head>
    <link href="vendor/mdi-font/css/material-design-iconic-font.min.css" rel="stylesheet" media="all">
    <link href="vendor/font-awesome-4.7/css/font-awesome.min.css" rel="stylesheet" media="all">
    <!-- Font special for pages-->
    <link href="https://fonts.googleapis.com/css?family=Poppins:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

    <!-- Vendor CSS-->
    <link href="vendor/select2/select2.min.css" rel="stylesheet" media="all">
    <link href="vendor/datepicker/daterangepicker.css" rel="stylesheet" media="all">

    <!-- Main CSS-->
    <link href="css/main.css" rel="stylesheet" media="all">
  </head>
    <style>
        @import url('https://fonts.googleapis.com/css?family=Poppins');

/* BASIC */

html {
 background-image: url("https://i.ibb.co/0mkdqnQ/online-proctoring-bg.jpg"); 
        -webkit-background-size: cover;
        -moz-background-size: cover;
        -o-background-size: cover;
        background-size: cover;
}

body {
  font-family: "Poppins", sans-serif;
  height: 100vh;
}

a {
  color: #92badd;
  display:inline-block;
  text-decoration: none;
  font-weight: 400;
}

h2 {
  text-align: center;
  font-size: 16px;
  font-weight: 600;
  text-transform: uppercase;
  display:inline-block;
  margin: 40px 8px 10px 8px; 
  color: #cccccc;
}



/* STRUCTURE */

.wrapper {
  display: flex;
  align-items: center;
  flex-direction: column; 
  justify-content: center;
  width: 100%;
  min-height: 100%;
  padding: 20px;
}

#formContent {
  -webkit-border-radius: 10px 10px 10px 10px;
  border-radius: 10px 10px 10px 10px;
  background: #fff;
  padding: 30px;
  width: 90%;
  max-width: 450px;
  position: relative;
  padding: 0px;
  -webkit-box-shadow: 0 30px 60px 0 rgba(0,0,0,0.3);
  box-shadow: 0 30px 60px 0 rgba(0,0,0,0.3);
  text-align: center;
}

#formFooter {
  background-color: #f6f6f6;
  border-top: 1px solid #dce8f1;
  padding: 25px;
  text-align: center;
  -webkit-border-radius: 0 0 10px 10px;
  border-radius: 0 0 10px 10px;
}



/* TABS */

h2.inactive {
  color: #cccccc;
}

h2.active {
  color: #0d0d0d;
  border-bottom: 2px solid #5fbae9;
}



/* FORM TYPOGRAPHY*/

input[type=button], input[type=submit], input[type=reset]  {
  background-color: #0f9d58;
  border: none;
  color: white;
  padding: 15px 80px;
  text-align: center;
  text-decoration: none;
  display: inline-block;
  text-transform: uppercase;
  font-size: 13px;
  -webkit-box-shadow: 0 10px 30px 0 rgba(95,186,233,0.4);
  box-shadow: 0 10px 30px 0 rgba(95,186,233,0.4);
  -webkit-border-radius: 5px 5px 5px 5px;
  border-radius: 5px 5px 5px 5px;
  margin: 5px 20px 40px 20px;
  -webkit-transition: all 0.3s ease-in-out;
  -moz-transition: all 0.3s ease-in-out;
  -ms-transition: all 0.3s ease-in-out;
  -o-transition: all 0.3s ease-in-out;
  transition: all 0.3s ease-in-out;
}

input[type=button]:hover, input[type=submit]:hover, input[type=reset]:hover  {
  background-color: green;
}

input[type=button]:active, input[type=submit]:active, input[type=reset]:active  {
  -moz-transform: scale(0.95);
  -webkit-transform: scale(0.95);
  -o-transform: scale(0.95);
  -ms-transform: scale(0.95);
  transform: scale(0.95);
}

input[type=text] {
  background-color: #f6f6f6;
  border: none;
  color: #0d0d0d;
  padding: 15px 32px;
  text-align: center;
  text-decoration: none;
  display: inline-block;
  font-size: 16px;
  margin: 5px;
  width: 85%;
  border: 2px solid #f6f6f6;
  -webkit-transition: all 0.5s ease-in-out;
  -moz-transition: all 0.5s ease-in-out;
  -ms-transition: all 0.5s ease-in-out;
  -o-transition: all 0.5s ease-in-out;
  transition: all 0.5s ease-in-out;
  -webkit-border-radius: 5px 5px 5px 5px;
  border-radius: 5px 5px 5px 5px;
}



input[type=password] {
  background-color: #f6f6f6;
  border: none;
  color: #0d0d0d;
  padding: 15px 32px;
  text-align: center;
  text-decoration: none;
  display: inline-block;
  font-size: 16px;
  margin: 5px;
  width: 85%;
  border: 2px solid #f6f6f6;
  -webkit-transition: all 0.5s ease-in-out;
  -moz-transition: all 0.5s ease-in-out;
  -ms-transition: all 0.5s ease-in-out;
  -o-transition: all 0.5s ease-in-out;
  transition: all 0.5s ease-in-out;
  -webkit-border-radius: 5px 5px 5px 5px;
  border-radius: 5px 5px 5px 5px;
}
input[type=email] {
  background-color: #f6f6f6;
  border: none;
  color: #0d0d0d;
  padding: 15px 32px;
  text-align: center;
  text-decoration: none;
  display: inline-block;
  font-size: 16px;
  margin: 5px;
  width: 85%;
  border: 2px solid #f6f6f6;
  -webkit-transition: all 0.5s ease-in-out;
  -moz-transition: all 0.5s ease-in-out;
  -ms-transition: all 0.5s ease-in-out;
  -o-transition: all 0.5s ease-in-out;
  transition: all 0.5s ease-in-out;
  -webkit-border-radius: 5px 5px 5px 5px;
  border-radius: 5px 5px 5px 5px;
}

input[type=text]:focus {
  background-color: #fff;
  border-bottom: 2px solid #5fbae9;
}

input[type=password]:focus {
  background-color: #fff;
  border-bottom: 2px solid #5fbae9;
}

input[type=text]:placeholder {
  color: #cccccc;
}



input[type=password]:placeholder {
  color: #cccccc;
}



/* ANIMATIONS */

/* Simple CSS3 Fade-in-down Animation */
.fadeInDown {
  -webkit-animation-name: fadeInDown;
  animation-name: fadeInDown;
  -webkit-animation-duration: 1s;
  animation-duration: 1s;
  -webkit-animation-fill-mode: both;
  animation-fill-mode: both;
}

@-webkit-keyframes fadeInDown {
  0% {
    opacity: 0;
    -webkit-transform: translate3d(0, -100%, 0);
    transform: translate3d(0, -100%, 0);
  }
  100% {
    opacity: 1;
    -webkit-transform: none;
    transform: none;
  }
}

@keyframes fadeInDown {
  0% {
    opacity: 0;
    -webkit-transform: translate3d(0, -100%, 0);
    transform: translate3d(0, -100%, 0);
  }
  100% {
    opacity: 1;
    -webkit-transform: none;
    transform: none;
  }
}

/* Simple CSS3 Fade-in Animation */
@-webkit-keyframes fadeIn { from { opacity:0; } to { opacity:1; } }
@-moz-keyframes fadeIn { from { opacity:0; } to { opacity:1; } }
@keyframes fadeIn { from { opacity:0; } to { opacity:1; } }

.fadeIn {
  opacity:0;
  -webkit-animation:fadeIn ease-in 1;
  -moz-animation:fadeIn ease-in 1;
  animation:fadeIn ease-in 1;

  -webkit-animation-fill-mode:forwards;
  -moz-animation-fill-mode:forwards;
  animation-fill-mode:forwards;

  -webkit-animation-duration:1s;
  -moz-animation-duration:1s;
  animation-duration:1s;
}

.fadeIn.first {
  -webkit-animation-delay: 0.4s;
  -moz-animation-delay: 0.4s;
  animation-delay: 0.4s;
}

.fadeIn.second {
  -webkit-animation-delay: 0.6s;
  -moz-animation-delay: 0.6s;
  animation-delay: 0.6s;
}

.fadeIn.third {
  -webkit-animation-delay: 0.8s;
  -moz-animation-delay: 0.8s;
  animation-delay: 0.8s;
}

.fadeIn.fourth {
  -webkit-animation-delay: 1s;
  -moz-animation-delay: 1s;
  animation-delay: 1s;
}

/* Simple CSS3 Fade-in Animation */
.underlineHover:after {
  display: block;
  left: 0;
  bottom: -10px;
  width: 0;
  height: 2px;
  background-color: #56baed;
  content: "";
  transition: width 0.2s;
}

.underlineHover:hover {
  color: #0d0d0d;
}

.underlineHover:hover:after{
  width: 100%;
}



/* OTHERS */

*:focus {
    outline: none;
} 

#icon {
  width:60%;
}

* {
  box-sizing: border-box;
}

.tablink {
  background-color: #555;
  color: white;
  float: left;
  border: none;
  outline: none;
  cursor: pointer;
  padding: 14px 16px;
  font-size: 17px;
  width: 25%;
}

.tablink:hover {
  background-color: #777;
}

/* Style the tab content (and add height:100% for full page content) */
.tabcontent {
  color: white;
  display: none;
  padding: 100px 20px;
  height: 100%;
  border-radius: 15px 15px 15px 15px;
}

#Home {background-color: white;}
#News {background-color: white;}

</style>
<div class="wrapper fadeInDown" style="background-image: url('global_assets/images/online-proctoring-bg.jpg');">
    <div >
      <!-- tabs -->
      <button class="tablink" style="border-radius: 9px 0 0 0; width:50%" onclick="openPage('Home', this, 'green')" id="defaultOpen">Login</button>
      <button class="tablink" style="border-radius: 0 9px 0 0;width:50%" onclick="openPage('News', this, 'green')">Register</button>

      <div id="Home" class="tabcontent" >
      <!-- Login Form -->
      <form action="/users/login/" method="POST">
        {% csrf_token %}
        <center><img style="width:200px;height:200px;margin-top:4px;margin-right:0px;margin-bottom:10px" src="https://i.ibb.co/sPS5YM5/Hack-logo.png"/>
        <input type="email" id="id_email" maxlength="60"  autofocus class="fadeIn second" name="email" placeholder="Email ID">
        <input type="password" id="id_password" maxlength="60" class="fadeIn third" name="password" placeholder="Password">
        <input type="submit" style="margin-top: 50px;" class="fadeIn fourth" value="Log In"><br></center>
        <!--<a class="underlineHover" href="#">Forgot Password</a>-->
      </form>
      </div>

      <div id="News" class="tabcontent">
        <form action="/users/signup/" method="POST">
          {% csrf_token %}
          
          <center><img style="width:400px;height:200px;margin-top:4px;margin-right:0px;margin-bottom:10px" src="https://i.ibb.co/dPNsksr/ProcExam.png"/>
          <div align="center">
            <img class="fadeIn second" src="https://i.ibb.co/JC1LKrC/user.png" width="215px" height="220px"  id="img"><br><br>
            <input type="file" accept="image/*" style="display:none;background-color:#4d8cf2;padding:8px;color" onchange="preview(event)" name="pic" id="pic" class="inputfile fadeIn second" required>
            <label class="fadeIn second"  id="label" style="background-color:#0f9d58;padding:8px;color:#fff;border: 2px solid #0f9d58;border-radius:9px;margin-top:20px;cursor:pointer;" for="pic" required>
              <i style="margin-top: 10px;" class="glyphicon glyphicon-open fadeIn second" required></i>&nbsp;Choose Image...</label><br>
            <p style="color:red" class="fadeIn second" id="msg"></p>
            </div>
          <input type="email" id="id_email" maxlength="60" autofocus class="fadeIn second" name="email" placeholder="Email ID"><br>
          <input type="text" id="id_username" maxlength="50" class="fadeIn second" name="username" placeholder="Username"><br>
          <input type="password" id="id_password1" autocomplete="new-password" class="fadeIn third" name="password1" placeholder="Enter Password"><br>
          <input type="password" id="id_password2" autocomplete="new-password" class="fadeIn fourth" name="password2" placeholder="Confirm Password"><br><br>

          <input type="submit" style="margin-top: 50px;" class="fadeIn fifth" value="Register"></center>
        
        </form>
      </div>

     
  
    </div>
  </div>
  <script>
    function verify(){
      document.getElementById("mybutton").addEventListener("click", function(event){
        event.preventDefault()
      });
      alert("register successful");
      document.getElementById("submit").submit();
    }

    function preview(event){
	var input = event.target.files[0];
	var reader = new FileReader();
	reader.onload = function(){
		var result = reader.result;
		var img = document.getElementById('img');
		img.src = result;
	}
	reader.readAsDataURL(input);
	
 }

  function openPage(pageName, elmnt, color) {
    // Hide all elements with class="tabcontent" by default */
    var i, tabcontent, tablinks;
    tabcontent = document.getElementsByClassName("tabcontent");
    for (i = 0; i < tabcontent.length; i++) {
      tabcontent[i].style.display = "none";
    }
  
    // Remove the background color of all tablinks/buttons
    tablinks = document.getElementsByClassName("tablink");
    for (i = 0; i < tablinks.length; i++) {
      tablinks[i].style.backgroundColor = "";
    }
  
    // Show the specific tab content
    document.getElementById(pageName).style.display = "block";
  
    // Add the specific color to the button used to open the tab content
    elmnt.style.backgroundColor = color;
  }
  
  // Get the element with id="defaultOpen" and click on it
  document.getElementById("defaultOpen").click();
</script>
</html>

app/proctool/users/templates/users/login_page.html
{% extends 'base.html' %}

<title>LogIn</title>
<head></head>
{% block one %}
<body>
<div>
  <h2><u>Log In</u></h2>
  <p>Enter your credentials:</p><br>
  <div style="text-align: center; margin: 0 auto;">
    <form action="{% url 'users:login' %}" method="POST" style="margin-left: 15%; margin-right: 15%; width: 70%;">
    {% csrf_token %}
    {% include 'bs4_form.html' with form=form %}
    {% if request.GET.next %}
        <input type="hidden" name="next" value="{{ request.GET.next }}">
    {% endif %}
    <input type="submit">
    </form>
    <p>Don't have an account? <a href="{% url 'users:signup' %}">Sign Up Here</p>
  </div>
</div>    
</body>        
{% endblock %}

app/proctool/users/templates/users/signup_page.html
{% extends 'base.html' %}

<title>SignUp</title>

{% block one %}
<div>
  <h2><u>Sign Up</u></h2>
  <p>Enter your details:</p><br>
  <div style="text-align: center; margin: 0 auto;">
    <form action="{% url 'users:signup' %}" method="POST" style="margin-left: 15%; margin-right: 15%; width: 70%;">
    {% csrf_token %}
    {% include 'bs4_form.html' with form=form %}  
    {% if request.GET.next %}
    {% endif %}
    <input type="submit">
    <p>Already have an account? <a href="{% url 'users:login' %}">Log In Here.</p>
    </form>
  </div>
</div>            
{% endblock %}